In [25]:
d1 = {'key1':[1,2,3,4,5,'ansh'],
     'key2':[7,8,9,10,11,12],
     'key3':[13,14,15,16,17,18],
     'key4':[19,20,21,22,23,24]
     }

In [11]:
import pandas as pd

In [27]:
df1 = pd.DataFrame(d1,index=['a','b','c','d','e','f'])

In [28]:
df1

key1  key2  key3  key4
a     1     7    13    19
b     2     8    14    20
c     3     9    15    21
d     4    10    16    22
e     5    11    17    23
f  ansh    12    18    24

In [29]:
d2 = {'key1':[1,2,3,4,5,"ansh"],
     'key2':[7,8,9,"ineuron",11,12],
     'key3':[13,14,15,'pwskills',17,18],
     'key4':[19,20,21,22,'FSDS2.0',24]
     }

In [30]:
df2 = pd.DataFrame(d2)

In [31]:
df2

key1     key2      key3     key4
0     1        7        13       19
1     2        8        14       20
2     3        9        15       21
3     4  ineuron  pwskills       22
4     5       11        17  FSDS2.0
5  ansh       12        18       24

In [35]:
pd.merge(df1,df2,how='left',on='key4')

key1_x  key2_x  key3_x key4 key1_y   key2_y    key3_y
0      1       7      13   19      1        7        13
1      2       8      14   20      2        8        14
2      3       9      15   21      3        9        15
3      4      10      16   22      4  ineuron  pwskills
4      5      11      17   23    NaN      NaN       NaN
5   ansh      12      18   24   ansh       12        18

In [36]:
pd.merge(df1,df2,how='right',on='key4')

/tmp/ipykernel_153/1236638062.py:1: FutureWarning: In a future version, the Index constructor will not infer numeric dtypes when passed object-dtype sequences (matching Series behavior)
  pd.merge(df1,df2,how='right',on='key4')


key1_x  key2_x  key3_x     key4 key1_y   key2_y    key3_y
0      1     7.0    13.0     19.0      1        7        13
1      2     8.0    14.0     20.0      2        8        14
2      3     9.0    15.0     21.0      3        9        15
3      4    10.0    16.0     22.0      4  ineuron  pwskills
4    NaN     NaN     NaN  FSDS2.0      5       11        17
5   ansh    12.0    18.0     24.0   ansh       12        18

In [37]:
pd.merge(df1,df2,how='outer',on='key4')

/tmp/ipykernel_153/573743905.py:1: FutureWarning: In a future version, the Index constructor will not infer numeric dtypes when passed object-dtype sequences (matching Series behavior)
  pd.merge(df1,df2,how='outer',on='key4')


key1_x  key2_x  key3_x     key4 key1_y   key2_y    key3_y
0      1     7.0    13.0     19.0      1        7        13
1      2     8.0    14.0     20.0      2        8        14
2      3     9.0    15.0     21.0      3        9        15
3      4    10.0    16.0     22.0      4  ineuron  pwskills
4      5    11.0    17.0     23.0    NaN      NaN       NaN
5   ansh    12.0    18.0     24.0   ansh       12        18
6    NaN     NaN     NaN  FSDS2.0      5       11        17

In [9]:
d11 = {'a':[1,2,3,4,5,'ansh'],
     'b':[7,8,9,10,11,12],
     'c':[13,14,15,16,17,18],
     'd':[19,20,21,22,23,24]
     }

In [12]:
df11 = pd.DataFrame(d11)

In [13]:
df11

a   b   c   d
0     1   7  13  19
1     2   8  14  20
2     3   9  15  21
3     4  10  16  22
4     5  11  17  23
5  ansh  12  18  24

In [14]:
d12 = {'key1':[1,2,3,4,5,"ansh"],
     'key2':[7,8,9,"ineuron",11,12],
     'key3':[13,14,15,'pwskills',17,18],
     'key4':[19,20,21,22,'FSDS2.0',24]
     }

In [15]:
df12 = pd.DataFrame(d12)

In [16]:
df12

key1     key2      key3     key4
0     1        7        13       19
1     2        8        14       20
2     3        9        15       21
3     4  ineuron  pwskills       22
4     5       11        17  FSDS2.0
5  ansh       12        18       24

In [17]:
pd.merge(df11,df12,how='left',left_on='a',right_on='key1')

a   b   c   d  key1     key2      key3     key4
0     1   7  13  19     1        7        13       19
1     2   8  14  20     2        8        14       20
2     3   9  15  21     3        9        15       21
3     4  10  16  22     4  ineuron  pwskills       22
4     5  11  17  23     5       11        17  FSDS2.0
5  ansh  12  18  24  ansh       12        18       24

In [56]:
d10 = {'key11':[1,2,3,4,5,'ansh'],
     'key21':[7,8,9,10,11,12],
     'key31':[13,14,15,16,17,18],
     'key41':[19,20,21,22,23,24]
     }

In [57]:
d20 = {'key1':[1,2,3,4,5,"ansh"],
     'key2':[7,8,9,"ineuron",11,12],
     'key3':[13,14,15,'pwskills',17,18],
     'key4':[19,20,21,22,'FSDS2.0',24]
     }

In [58]:
df10 = pd.DataFrame(d10,index=[1,2,3,4,5,6])

In [64]:
df20 = pd.DataFrame(d20,index=[1,2,3,4,5,'ansh'])

In [66]:
df10.join(df20,how='right')

key11  key21  key31  key41  key1     key2      key3     key4
1        1    7.0   13.0   19.0     1        7        13       19
2        2    8.0   14.0   20.0     2        8        14       20
3        3    9.0   15.0   21.0     3        9        15       21
4        4   10.0   16.0   22.0     4  ineuron  pwskills       22
5        5   11.0   17.0   23.0     5       11        17  FSDS2.0
ansh   NaN    NaN    NaN    NaN  ansh       12        18       24

In [67]:
df10.join(df20)

key11  key21  key31  key41 key1     key2      key3     key4
1     1      7     13     19    1        7        13       19
2     2      8     14     20    2        8        14       20
3     3      9     15     21    3        9        15       21
4     4     10     16     22    4  ineuron  pwskills       22
5     5     11     17     23    5       11        17  FSDS2.0
6  ansh     12     18     24  NaN      NaN       NaN      NaN

In [68]:
df10.join(df20,how='outer')

key11  key21  key31  key41  key1     key2      key3     key4
1        1    7.0   13.0   19.0     1        7        13       19
2        2    8.0   14.0   20.0     2        8        14       20
3        3    9.0   15.0   21.0     3        9        15       21
4        4   10.0   16.0   22.0     4  ineuron  pwskills       22
5        5   11.0   17.0   23.0     5       11        17  FSDS2.0
6     ansh   12.0   18.0   24.0   NaN      NaN       NaN      NaN
ansh   NaN    NaN    NaN    NaN  ansh       12        18       24

In [69]:
df10.join(df20,how='inner')

key11  key21  key31  key41 key1     key2      key3     key4
1     1      7     13     19    1        7        13       19
2     2      8     14     20    2        8        14       20
3     3      9     15     21    3        9        15       21
4     4     10     16     22    4  ineuron  pwskills       22
5     5     11     17     23    5       11        17  FSDS2.0

In [70]:
pd.concat([df10,df20],axis=0)

key11  key21  key31  key41  key1     key2      key3     key4
1        1    7.0   13.0   19.0   NaN      NaN       NaN      NaN
2        2    8.0   14.0   20.0   NaN      NaN       NaN      NaN
3        3    9.0   15.0   21.0   NaN      NaN       NaN      NaN
4        4   10.0   16.0   22.0   NaN      NaN       NaN      NaN
5        5   11.0   17.0   23.0   NaN      NaN       NaN      NaN
6     ansh   12.0   18.0   24.0   NaN      NaN       NaN      NaN
1      NaN    NaN    NaN    NaN     1        7        13       19
2      NaN    NaN    NaN    NaN     2        8        14       20
3      NaN    NaN    NaN    NaN     3        9        15       21
4      NaN    NaN    NaN    NaN     4  ineuron  pwskills       22
5      NaN    NaN    NaN    NaN     5       11        17  FSDS2.0
ansh   NaN    NaN    NaN    NaN  ansh       12        18       24

In [71]:
pd.concat([df1,df2],axis=0)

key1     key2      key3     key4
a     1        7        13       19
b     2        8        14       20
c     3        9        15       21
d     4       10        16       22
e     5       11        17       23
f  ansh       12        18       24
0     1        7        13       19
1     2        8        14       20
2     3        9        15       21
3     4  ineuron  pwskills       22
4     5       11        17  FSDS2.0
5  ansh       12        18       24

In [72]:
pd.concat([df1,df2],axis=1)

key1  key2  key3  key4  key1     key2      key3     key4
a     1   7.0  13.0  19.0   NaN      NaN       NaN      NaN
b     2   8.0  14.0  20.0   NaN      NaN       NaN      NaN
c     3   9.0  15.0  21.0   NaN      NaN       NaN      NaN
d     4  10.0  16.0  22.0   NaN      NaN       NaN      NaN
e     5  11.0  17.0  23.0   NaN      NaN       NaN      NaN
f  ansh  12.0  18.0  24.0   NaN      NaN       NaN      NaN
0   NaN   NaN   NaN   NaN     1        7        13       19
1   NaN   NaN   NaN   NaN     2        8        14       20
2   NaN   NaN   NaN   NaN     3        9        15       21
3   NaN   NaN   NaN   NaN     4  ineuron  pwskills       22
4   NaN   NaN   NaN   NaN     5       11        17  FSDS2.0
5   NaN   NaN   NaN   NaN  ansh       12        18       24

In [73]:
## NUMPY

In [3]:
import numpy as np

In [75]:
l = [1,2,3,4,5,6]

In [76]:
type(l)

list

In [77]:
a = np.array(l)

In [78]:
type(a)

numpy.ndarray

In [79]:
a

array([1, 2, 3, 4, 5, 6])

In [80]:
a1 = np.array([[1,2,3] , [3,4,5]])

In [81]:
a1

array([[1, 2, 3],
       [3, 4, 5]])

In [87]:
a2 = np.array([[[4,5,6] , [7,8,9]]])

In [88]:
a2

array([[[4, 5, 6],
        [7, 8, 9]]])

In [89]:
a.ndim

1

In [90]:
a1.ndim

2

In [91]:
a2.ndim

3

In [92]:
a3 = np.array([[[1,2,3],[4,5,6],[7,8,9],[10,11,12]]])

In [93]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]]])

In [94]:
a3.ndim

3

In [4]:
l1 = [1,2,3,4]

In [5]:
a = np.asarray(l1)

In [6]:
m = np.matrix(l1)

In [8]:
np.asanyarray(l1)

array([1, 2, 3, 4])

In [18]:
np.asanyarray(a)

array([1, 2, 3, 4])

In [19]:
np.asanyarray(m)

matrix([[1, 2, 3, 4]])

In [20]:
a

array([1, 2, 3, 4])

In [21]:
a1 = a

In [22]:
a1

array([1, 2, 3, 4])

In [24]:
a[0] = 10

In [25]:
a

array([10,  2,  3,  4])

In [96]:
np.fromfunction(lambda i,j : i==j,(4,4))

array([[ True, False, False, False],
       [False,  True, False, False],
       [False, False,  True, False],
       [False, False, False,  True]])

In [97]:
np.random.rand(2,3)

array([[0.52670411, 0.89314186, 0.17137606],
       [0.5786144 , 0.62025888, 0.89493201]])

In [112]:
d = np.random.randint(0,10,(4,4,2))

In [111]:
np.random.randn(3,4,4)

array([[[ 0.14209413,  0.4167271 ,  0.21476493,  1.06781936],
        [-1.63212872,  0.54797881, -0.14135219, -1.33973694],
        [-1.2356468 ,  1.11719964, -0.09205213,  0.33026572],
        [ 0.07427508,  0.6166103 , -1.37633561, -2.03089583]],

       [[ 1.60835012,  0.31861098,  1.07329253,  0.66703143],
        [-0.98228985,  0.26371492, -0.33594086, -0.60743536],
        [ 0.34972747,  0.44343831,  1.20215363,  0.47594161],
        [-0.56296037,  0.25962827, -0.25982883, -2.35843153]],

       [[ 0.32022484,  0.37812797, -0.08872543, -0.65558965],
        [-1.45816694, -0.9507649 ,  0.61519646,  1.52929335],
        [ 0.72421203, -0.60526616, -0.30092193, -0.73535856],
        [ 0.14843474, -1.62827819,  0.82144176, -1.12490431]]])

In [113]:
d.reshape(16,2)

array([[3, 5],
       [4, 9],
       [9, 2],
       [4, 1],
       [7, 1],
       [8, 2],
       [2, 7],
       [2, 9],
       [7, 3],
       [3, 9],
       [4, 1],
       [4, 9],
       [3, 0],
       [7, 5],
       [9, 4],
       [7, 7]])

In [115]:
pd.DataFrame(d.reshape(16,2))

0  1
0   3  5
1   4  9
2   9  2
3   4  1
4   7  1
5   8  2
6   2  7
7   2  9
8   7  3
9   3  9
10  4  1
11  4  9
12  3  0
13  7  5
14  9  4
15  7  7