In [1]:
#Numpy
import numpy as np

In [2]:
range(10)

range(0, 10)

In [3]:
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [8]:
list(range(4,8))

[4, 5, 6, 7]

In [11]:
np.arange(0.5,8)

array([0.5, 1.5, 2.5, 3.5, 4.5, 5.5, 6.5, 7.5])

In [12]:
np.arange(5,-4,-.5)

array([ 5. ,  4.5,  4. ,  3.5,  3. ,  2.5,  2. ,  1.5,  1. ,  0.5,  0. ,
       -0.5, -1. , -1.5, -2. , -2.5, -3. , -3.5])

In [14]:
np.linspace(1,5,20)

array([1.        , 1.21052632, 1.42105263, 1.63157895, 1.84210526,
       2.05263158, 2.26315789, 2.47368421, 2.68421053, 2.89473684,
       3.10526316, 3.31578947, 3.52631579, 3.73684211, 3.94736842,
       4.15789474, 4.36842105, 4.57894737, 4.78947368, 5.        ])

In [15]:
np.logspace(1,5,10)

array([1.00000000e+01, 2.78255940e+01, 7.74263683e+01, 2.15443469e+02,
       5.99484250e+02, 1.66810054e+03, 4.64158883e+03, 1.29154967e+04,
       3.59381366e+04, 1.00000000e+05])

In [17]:
np.zeros((1,5,2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

In [18]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [21]:
np.ones((2,4,2)) + 2

array([[[3., 3.],
        [3., 3.],
        [3., 3.],
        [3., 3.]],

       [[3., 3.],
        [3., 3.],
        [3., 3.],
        [3., 3.]]])

In [22]:
np.empty((2,3))

array([[4.68725153e-310, 0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000]])

In [25]:
a=np.eye(4)

In [26]:
a.shape

(4, 4)

In [27]:
a.size

16

In [28]:
a.ndim

2

In [29]:
a1 = np.random.randn(3,4)

In [30]:
a1

array([[-0.83571939, -0.64796182, -0.84989578,  0.12258442],
       [-0.4710396 ,  1.0829194 , -0.65329015,  2.09681253],
       [ 0.64734009, -0.83170459, -0.37054747,  2.36762198]])

In [31]:
import pandas as pd

In [32]:
pd.DataFrame(a1)

0         1         2         3
0 -0.835719 -0.647962 -0.849896  0.122584
1 -0.471040  1.082919 -0.653290  2.096813
2  0.647340 -0.831705 -0.370547  2.367622

In [35]:
a1[1][1]

1.0829194031052158

In [37]:
a1[0:2,0:2]

array([[-0.83571939, -0.64796182],
       [-0.4710396 ,  1.0829194 ]])

In [47]:
a1[[0,1],0:2]

array([[-0.83571939, -0.64796182],
       [-0.4710396 ,  1.0829194 ]])

In [40]:
m1 = np.random.randint(1,3,(3,3))

In [41]:
m1

array([[1, 1, 2],
       [2, 1, 1],
       [2, 1, 2]])

In [42]:
m2 = np.random.randint(2,4,(3,3))

In [43]:
m2

array([[2, 2, 3],
       [3, 2, 2],
       [3, 2, 3]])

In [44]:
m1*m2

array([[2, 2, 6],
       [6, 2, 2],
       [6, 2, 6]])

In [48]:
m1@m2

array([[11,  8, 11],
       [10,  8, 11],
       [13, 10, 14]])

In [49]:
pow(m1,4)

array([[ 1,  1, 16],
       [16,  1,  1],
       [16,  1, 16]])

In [50]:
np.sqrt(m1)

array([[1.        , 1.        , 1.41421356],
       [1.41421356, 1.        , 1.        ],
       [1.41421356, 1.        , 1.41421356]])

In [51]:
np.log(m1)

array([[0.        , 0.        , 0.69314718],
       [0.69314718, 0.        , 0.        ],
       [0.69314718, 0.        , 0.69314718]])

In [52]:
np.exp(m1)

array([[2.71828183, 2.71828183, 7.3890561 ],
       [7.3890561 , 2.71828183, 2.71828183],
       [7.3890561 , 2.71828183, 7.3890561 ]])